CREATE TABLE COUNTRY
(
	Cnumber			INT IDENTITY(1,1)	NOT NULL,
	CountryName		VARCHAR(30)			NOT NULL,
	Flag			VARCHAR(250),
	UNIQUE(CountryName),
	PRIMARY KEY(Cnumber)
);

CREATE TABLE ATHLETE
(
	Aemail			VARCHAR(25)		NOT NULL,
	Apassword		VARCHAR(16)		NOT NULL,
	Fname			VARCHAR(15)		NOT NULL,
	Mname			VARCHAR(15),
	Lname1			VARCHAR(15)		NOT NULL,
	Lname2			VARCHAR(15)		NOT NULL,
	Photo			VARBINARY(MAX),
	Cno				INT				NOT NULL,
	Birth_date		DATE			NOT NULL,
	PRIMARY KEY(Aemail)
);

CREATE TABLE FOLLOWS
(
	Afollower	VARCHAR(25)		NOT NULL,
	Afollows	VARCHAR(25)		NOT NULL,
	PRIMARY KEY(Afollower, Afollows)
);

CREATE TABLE SPORT
(
	SportID			INT IDENTITY(1,1)	NOT NULL,
	SportName		VARCHAR(10)			NOT NULL,
	UNIQUE(SportName),
	PRIMARY KEY(SportID)
);

CREATE TABLE PRIVACY
(
	PrivacyID		INT IDENTITY(1,1)	NOT NULL,
	PRIMARY KEY(PrivacyID)
);

CREATE TABLE RACE
(
	RaceID		INT IDENTITY(1,1)		NOT NULL,
	Rname		VARCHAR(50)				NOT NULL,
	Price		DECIMAL(7,2)			NOT NULL,
	Rdate		DATE					NOT NULL,
	Rroute		XML,
	Pid			INT						NOT NULL,
	Sptid		INT						NOT NULL,
	PRIMARY KEY(RaceID)
);

CREATE TABLE RACE_BANKACCS
(
	Rid			INT				NOT NULL,
	Account		INT			NOT NULL,
	PRIMARY KEY(Rid, Account)
);

CREATE TABLE INSCRIPTION
(
	Inumber		INT IDENTITY(1,1)		NOT NULL,
	Accepted	BIT						DEFAULT 0,
	Auser		VARCHAR(25)				NOT NULL,
	Rid			INT						NOT NULL,
	PRIMARY KEY(Inumber)
);

CREATE TABLE CHALLENGE
(
	ChallengeID		INT IDENTITY(1,1)	NOT NULL,
	Cname			VARCHAR(50)			NOT NULL,
	Ctype			VARCHAR(8)			NOT NULL,
	StartDate		DATE				NOT NULL,
	FinalDate		DATE				NOT NULL,
	Pid				INT					NOT NULL,
	Sptid			INT					NOT NULL,
	Mileage			SMALLINT			NOT NULL,
	PRIMARY KEY(ChallengeID)
);

CREATE TABLE ACTIVITY
(
	ActivityID		INT IDENTITY(1,1)	NOT NULL,
	Adate			DATE				NOT NULL,
	Ahour			TIME				NOT NULL,
	Aduration		TIME				NOT NULL,
	Mileage			TINYINT				NOT NULL,
	Aroute			XML,
	Auser			VARCHAR(25)			NOT NULL,
	Rid				INT					NOT NULL,
	Challid			INT					NOT NULL,
	Sptid			INT					NOT NULL,
	PRIMARY KEY(ActivityID)
);

CREATE TABLE COMMENT
(
	Auser			VARCHAR(25)			NOT NULL,
	Actid			INT					NOT NULL,
	Content			VARCHAR(150)		NOT NULL,
	PRIMARY KEY(Auser, Actid, Content)
);

CREATE TABLE CATEGORY
(
	CategoryID		INT IDENTITY(1,1)	NOT NULL,
	CategoryName	VARCHAR(8)			NOT NULL,
	Descr			VARCHAR(35)			NOT NULL,
	UNIQUE(CategoryName),
	PRIMARY KEY(CategoryID)
);

CREATE TABLE SPONSOR
(
	SponsorID		INT IDENTITY(1,1)	NOT NULL,
	Sname			VARCHAR(50)			NOT NULL,
	Phone			VARCHAR(15)			NOT NULL,
	Logo			VARCHAR(250)		NOT NULL,
	Agent			VARCHAR(60)			NOT NULL,
	UNIQUE(Sname),
	PRIMARY KEY(SponsorID)
);

CREATE TABLE ATHLETE_CHALLENGE
(
	Auser			VARCHAR(25)			NOT NULL,
	Challid			INT					NOT NULL,
	PRIMARY KEY(Auser, Challid)
);

CREATE TABLE RACE_CATEGORY
(
	Rid			INT		NOT NULL,
	Catid		INT		NOT NULL,
	PRIMARY KEY(Rid, Catid)
);

CREATE TABLE RACE_SPONSOR
(
	Rid			INT		NOT NULL,
	Spnid		INT		NOT NULL,
	PRIMARY KEY(Rid, Spnid)
);

CREATE TABLE CHALLENGE_SPONSOR
(
	Challid		INT		NOT NULL,
	Spnid		INT		NOT NULL,
	PRIMARY KEY(Challid, Spnid)
);

CREATE TABLE ORGANIZER
(
	Oemail			VARCHAR(25)		NOT NULL,
	Opassword		VARCHAR(16)		NOT NULL,
	PRIMARY KEY(Oemail)
);

CREATE TABLE SGROUP
(
	GroupID		INT	IDENTITY(1,1)	NOT NULL,
	Gname		VARCHAR(50)			NOT NULL,
	Ouser		VARCHAR(25)			NOT NULL,
	Logo		VARCHAR(250),
	UNIQUE(Gname),
	PRIMARY KEY(GroupID)
);

CREATE TABLE ATHLETE_GROUP
(
	Auser	VARCHAR(25)		NOT NULL,
	Gid		INT				NOT NULL,
	PRIMARY KEY(Auser, Gid)
);

CREATE TABLE GROUP_PRIVACY
(
	Gid		INT		NOT NULL,
	Pid		INT		NOT NULL,
	PRIMARY KEY(Gid, Pid)
);

ALTER TABLE FOLLOWS
ADD CONSTRAINT FOLLOWER_FK
FOREIGN KEY (Afollower) REFERENCES ATHLETE(Aemail)
ON DELETE CASCADE;

ALTER TABLE FOLLOWS
ADD CONSTRAINT FOLLOWS_FK
FOREIGN KEY (Afollows) REFERENCES ATHLETE(Aemail);

ALTER TABLE ATHLETE
ADD CONSTRAINT ATHLETE_COUNTRY_FK
FOREIGN KEY (Cno) REFERENCES COUNTRY(Cnumber);

ALTER TABLE ACTIVITY
ADD CONSTRAINT ACTIVITY_ATHLETE_FK
FOREIGN KEY (Auser) REFERENCES ATHLETE(Aemail)
ON DELETE CASCADE;

ALTER TABLE ACTIVITY
ADD CONSTRAINT ACTIVITY_RACE_FK
FOREIGN KEY (Rid) REFERENCES RACE(RaceID);

ALTER TABLE ACTIVITY
ADD CONSTRAINT ACTIVITY_CHALLENGE_FK
FOREIGN KEY (Challid) REFERENCES CHALLENGE(ChallengeID);

ALTER TABLE ACTIVITY
ADD CONSTRAINT ACTIVITY_SPORT_FK
FOREIGN KEY (Sptid) REFERENCES SPORT(SportID);

ALTER TABLE INSCRIPTION
ADD CONSTRAINT INSCRIPTION_ATHLETE_FK
FOREIGN KEY (Auser) REFERENCES ATHLETE(Aemail)
ON DELETE CASCADE;

ALTER TABLE INSCRIPTION
ADD CONSTRAINT INSCRIPTION_RACE_FK
FOREIGN KEY (Rid) REFERENCES RACE(RaceID)
ON DELETE CASCADE;

ALTER TABLE RACE
ADD CONSTRAINT RACE_PRIVACY_FK
FOREIGN KEY (Pid) REFERENCES PRIVACY(PrivacyID);

ALTER TABLE RACE
ADD CONSTRAINT RACE_SPORT_FK
FOREIGN KEY (Sptid) REFERENCES SPORT(SportID);

ALTER TABLE COMMENT
ADD CONSTRAINT COMMENT_ATHLETE_FK
FOREIGN KEY (Auser) REFERENCES ATHLETE(Aemail)
ON DELETE CASCADE;

ALTER TABLE COMMENT
ADD CONSTRAINT COMMENT_ACTIVITY_FK
FOREIGN KEY (Actid) REFERENCES ACTIVITY(ActivityID);

ALTER TABLE RACE_BANKACCS
ADD CONSTRAINT RACE_BANKACCS_RACE_FK
FOREIGN KEY (Rid) REFERENCES RACE(RaceID)
ON DELETE CASCADE;

ALTER TABLE CHALLENGE
ADD CONSTRAINT CHALLENGE_PRIVACY_FK
FOREIGN KEY (Pid) REFERENCES PRIVACY(PrivacyID);

ALTER TABLE CHALLENGE
ADD CONSTRAINT CHALLENGE_SPORT_FK
FOREIGN KEY (Sptid) REFERENCES SPORT(SportID);

ALTER TABLE ATHLETE_CHALLENGE
ADD CONSTRAINT ATHLETE_CHALLENGE_ATHLETE_FK
FOREIGN KEY (Auser) REFERENCES ATHLETE(Aemail)
ON DELETE CASCADE;

ALTER TABLE ATHLETE_CHALLENGE
ADD CONSTRAINT ATHLETE_CHALLENGE_CHALLENGE_FK
FOREIGN KEY (Challid) REFERENCES CHALLENGE(ChallengeID)
ON DELETE CASCADE;

ALTER TABLE SGROUP
ADD CONSTRAINT GROUP_ORGANIZER_FK
FOREIGN KEY (Ouser) REFERENCES ORGANIZER(Oemail)
ON DELETE CASCADE;

ALTER TABLE RACE_CATEGORY
ADD CONSTRAINT RACE_CATEGORY_RACE_FK
FOREIGN KEY (Rid) REFERENCES RACE(RaceID)
ON DELETE CASCADE;

ALTER TABLE RACE_CATEGORY
ADD CONSTRAINT RACE_CATEGORY_CATEGORY_FK
FOREIGN KEY (Catid) REFERENCES CATEGORY(CategoryID)
ON DELETE CASCADE;

ALTER TABLE RACE_SPONSOR
ADD CONSTRAINT RACE_SPONSOR_RACE_FK
FOREIGN KEY (Rid) REFERENCES RACE(RaceID)
ON DELETE CASCADE;

ALTER TABLE RACE_SPONSOR
ADD CONSTRAINT RACE_SPONSOR_SPONSOR_FK
FOREIGN KEY (Spnid) REFERENCES SPONSOR(SponsorID)
ON DELETE CASCADE;

ALTER TABLE CHALLENGE_SPONSOR
ADD CONSTRAINT CHALLENGE_SPONSOR_CHALLENGE_FK
FOREIGN KEY (Challid) REFERENCES CHALLENGE(ChallengeID)
ON DELETE CASCADE;

ALTER TABLE CHALLENGE_SPONSOR
ADD CONSTRAINT CHALLENGE_SPONSOR_SPONSOR_FK
FOREIGN KEY (Spnid) REFERENCES SPONSOR(SponsorID)
ON DELETE CASCADE;

ALTER TABLE ATHLETE_GROUP
ADD CONSTRAINT ATHLETE_GROUP_ATHLETE_FK
FOREIGN KEY (Auser) REFERENCES ATHLETE(Aemail)
ON DELETE CASCADE;

ALTER TABLE ATHLETE_GROUP
ADD CONSTRAINT ATHLETE_GROUP_GROUP_FK
FOREIGN KEY (Gid) REFERENCES SGROUP(GroupID)
ON DELETE CASCADE;

ALTER TABLE GROUP_PRIVACY
ADD CONSTRAINT GROUP_PRIVACY_GROUP_FK
FOREIGN KEY (Gid) REFERENCES SGROUP(GroupID)
ON DELETE CASCADE;

ALTER TABLE GROUP_PRIVACY
ADD CONSTRAINT GROUP_PRIVACY_PRIVACY_FK
FOREIGN KEY (Pid) REFERENCES PRIVACY(PrivacyID)
ON DELETE CASCADE;
GO
CREATE VIEW ActivitySportView AS
SELECT 
    A.ActivityID,
    A.Adate,
    A.Ahour,
    A.Aduration,
    A.Mileage,
    A.Aroute,
    A.Auser,
    A.Rid,
    A.Challid,
    A.Sptid,
    S.SportID,
    S.SportName
FROM ACTIVITY A
JOIN SPORT S ON A.Sptid = S.SportID;
